AllCops:
  TargetRubyVersion: 2.4.1
  Exclude:
    - 'vendor/**/*'
    - 'test/dummy/db/schema.rb'
    - 'node_modules/**/*'

Metrics/LineLength:
  Max: 120

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/DotPosition:
  EnforcedStyle: trailing

Style/TrailingCommaInArguments:
  # If `comma`, the cop requires a comma after the last argument, but only for
  # parenthesized method calls where each argument is on its own line.
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  # If `comma`, the cop requires a comma after the last item in an array or
  # hash, but only when each item is on its own line.
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  # If `comma`, the cop requires a comma after the last item in an array or
  # hash, but only when each item is on its own line.
  EnforcedStyleForMultiline: comma

Style/MutableConstant:
  Enabled: false
Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: true
  PreferredDelimiters:
    default: ()
    '%i': '()'
    '%I': '()'
    '%r': '{}'
    '%w': '()'
    '%W': '()'
Style/EmptyMethod:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Metrics/ParameterLists:
  Exclude:
    - 'app/forms/*.rb'
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
